---
# tasks file for sdkperf-java
- name: Copy sdkperf to worker nodes
  copy:
    src: sdkperf-jcsmp-8.4.1.8
    dest: .
    owner: ubuntu
    mode: "0644"

- name: Give sdkperf execute permissions
  become: true
  command: chmod -R +x sdkperf-jcsmp-8.4.1.8
