---
# tasks file for sdkperf-c-x64
- name: Copy sdkperf to worker nodes
  copy:
    src: sdkperf-c-x64
    dest: .
    owner: ubuntu
    mode: "0644"

- name: Give sdkperf execute permissions
  become: true
  command: chmod -R +x sdkperf-c-x64
